//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewGoShoes.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GoShoesDBEntities : DbContext
    {
        public GoShoesDBEntities()
            : base("name=GoShoesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T__ordersDetail> T__ordersDetail { get; set; }
        public DbSet<T_buyCar> T_buyCar { get; set; }
        public DbSet<T_callMe> T_callMe { get; set; }
        public DbSet<T_order> T_order { get; set; }
        public DbSet<T_shoes> T_shoes { get; set; }
        public DbSet<T_shoesType> T_shoesType { get; set; }
        public DbSet<T_user> T_user { get; set; }
        public DbSet<T_userType> T_userType { get; set; }
        public DbSet<T_userWords> T_userWords { get; set; }
    }
}
