//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewGoShoes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_order
    {
        public T_order()
        {
            this.T__ordersDetail = new HashSet<T__ordersDetail>();
        }
    
        public int orderId { get; set; }
        public System.DateTime ordersDate { get; set; }
        public int userId { get; set; }
    
        public virtual ICollection<T__ordersDetail> T__ordersDetail { get; set; }
        public virtual T_user T_user { get; set; }
    }
}
