//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewGoShoes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_shoesType
    {
        public T_shoesType()
        {
            this.T_shoes = new HashSet<T_shoes>();
        }
    
        public int shoesTypeId { get; set; }
        public string shoesTypeName { get; set; }
    
        public virtual ICollection<T_shoes> T_shoes { get; set; }
    }
}
