//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewGoShoes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_user
    {
        public T_user()
        {
            this.T_order = new HashSet<T_order>();
            this.T_userWords = new HashSet<T_userWords>();
            this.T_buyCar = new HashSet<T_buyCar>();
        }
    
        public int userId { get; set; }
        public string userName { get; set; }
        public string userPassword { get; set; }
        public int userPowerId { get; set; }
        public int userClose { get; set; }
    
        public virtual ICollection<T_order> T_order { get; set; }
        public virtual T_userType T_userType { get; set; }
        public virtual ICollection<T_userWords> T_userWords { get; set; }
        public virtual ICollection<T_buyCar> T_buyCar { get; set; }
    }
}
