//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewGoShoes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_userType
    {
        public T_userType()
        {
            this.T_user = new HashSet<T_user>();
        }
    
        public int userPowerId { get; set; }
        public string userPowerName { get; set; }
    
        public virtual ICollection<T_user> T_user { get; set; }
    }
}
